version: '2'
services:
  db:
    image: mariadb:10.3
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=orocrm
  web:
    build: web
    image: bebehei/orocrm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
    env_file:
      - env_general
